INSERT INTO USUARIOS(USERNAME, PASSWORD, ENABLED, NOMBRE, APELLIDO, EMAIL) VALUES('carlos', '123456', 1, 'Carlos', 'Zapata', 'carlos@correo.com');
INSERT INTO USUARIOS(USERNAME, PASSWORD, ENABLED, NOMBRE, APELLIDO, EMAIL) VALUES('admin', '123456', 1, 'Fernando', 'Gomez', 'fernando@correo.com');

INSERT INTO ROLES(NOMBRE) VALUES('ROLE_USER');
INSERT INTO ROLES(NOMBRE) VALUES('ROLE_ADMIN');

INSERT INTO USUARIOS_ROLES(USUARIO_ID, ROLE_ID) VALUES(1, 1);
INSERT INTO USUARIOS_ROLES(USUARIO_ID, ROLE_ID) VALUES(2, 2);
INSERT INTO USUARIOS_ROLES(USUARIO_ID, ROLE_ID) VALUES(2, 1);