spring:
  application:
    name: servicio-zuul-server
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
#Se usa para centralizar el acceso a todos los microservicios registrados en Eureka
#Se asigna una ruta base o prefijo para a cada microservicio para acceder      
zuul:
  routes:
    productos:
      service-id: servicio-productos     
      path: /api/productos/**   
    items:
      service-id: servicio-items
      path: /api/items/**    
      
#Tiempo de espera por si se genera un timeout     
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000
#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 60000      