server:
  port: ${PORT:0}
spring:
  application:
    name: servicio-productos 
#Enviar el 1.0 es decir el 100% de las trazas de los request    
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   
       
  #Configuracion para que se agregue un puerto aleatorio en vez de difinirlo
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}