INSERT INTO productos(NOMBRE, PRECIO, CREATE_AT) VALUES('Panasonic', 800, NOW());
INSERT INTO productos(NOMBRE, PRECIO, CREATE_AT) VALUES('Sony', 700, NOW());
INSERT INTO productos(NOMBRE, PRECIO, CREATE_AT) VALUES('Apple', 1000, NOW());
INSERT INTO productos(NOMBRE, PRECIO, CREATE_AT) VALUES('Sony Notebook', 1000, NOW());
INSERT INTO productos(NOMBRE, PRECIO, CREATE_AT) VALUES('HP', 500, NOW());
INSERT INTO productos(NOMBRE, PRECIO, CREATE_AT) VALUES('Nike', 100, NOW());
INSERT INTO productos(NOMBRE, PRECIO, CREATE_AT) VALUES('Adidas', 200, NOW());
INSERT INTO productos(NOMBRE, PRECIO, CREATE_AT) VALUES('Reebok', 300, NOW());
