#file:/home/usuario/Documentos/SpringProjects/config
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/karlozeta/config-server.git
server:
  port: 8888
#Se agrega username y password cuando el repositorio sea privado            
#          username: karlozeta
#          password: Ghmz.7328      